[package]
name = "console-draw"
description = "Shared terminal drawing code library"
version = "0.1.0"
edition = "2021"

[dependencies]
alacritty_terminal = { version = "0.26.0", default-features = false }
drm.workspace = true
orbclient.workspace = true
psf-rs.workspace = true

graphics-ipc = { path = "../graphics-ipc" }

[features]
default = []

[lints]
workspace = true
