workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_NAMESPACE == "redox-os"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

stages:
  - build
  - cross-build
  - test

fmt:
    stage: build
    script:
        - rustup component add rustfmt
        - CHECK_ONLY=1 ./fmt.sh

x86_64:
    stage: build
    script:
        - ./check.sh

x86_64:clippy:
    stage: build
    needs: [x86_64]
    # TODO: remove
    allow_failure: true
    script:
        # TODO: remove when most warnings are gone
        - export RUSTFLAGS=-Awarnings
        - ./check.sh --clippy

i586:
    stage: cross-build
    script:
        - ./check.sh --arch=i586

aarch64:
    stage: cross-build
    image: registry.redox-os.org/redox-os/redoxer:aarch64
    script:
        - ./check.sh --arch=aarch64

riscv64gc:
    stage: cross-build
    script:
        - ./check.sh --arch=riscv64gc

boot:
    stage: test
    needs: [x86_64]
    script:
        - timeout -s KILL 9m ./check.sh --test
